# Generated by Django 4.1 on 2022-08-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='Адрес эл. почты')),
                ('stuff', models.CharField(max_length=100, verbose_name='Желаемая должность')),
                ('message', models.TextField(verbose_name='Сопроводительное письмо')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Автор комментария')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('food_count', models.IntegerField(default=None, null=None, verbose_name='Кол-во')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, null=None, verbose_name='Время заказа')),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Адрес эл. почты')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(verbose_name='звезда')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер звезды')),
            ],
        ),
        migrations.RemoveField(
            model_name='foods',
            name='rating',
        ),
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(default=None, null=None, upload_to='', verbose_name='Фотография продукта'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название еды'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена еды'),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foods', verbose_name='еда'),
        ),
        migrations.AddField(
            model_name='orders',
            name='food',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='main.foods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foods'),
        ),
    ]
