# Generated by Django 4.0.4 on 2022-08-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_name_alter_foods_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_count', models.IntegerField(default=0, verbose_name='Количество еды')),
                ('total_price', models.IntegerField(verbose_name='Итого')),
                ('food', models.ManyToManyField(to='main.foods')),
            ],
        ),
    ]
