# Generated by Django 4.0.4 on 2022-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(default=None, null=None, verbose_name='Итого'),
        ),
    ]
