# Generated by Django 4.0.4 on 2022-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_basket_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('price', models.IntegerField(verbose_name='Сумма')),
                ('food', models.ManyToManyField(to='main.foods')),
            ],
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
