# Generated by Django 4.0.4 on 2022-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orders_delete_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='food_count',
            field=models.IntegerField(default=None, null=None, verbose_name='Кол-во'),
        ),
    ]
