# Generated by Django 4.0.4 on 2022-08-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orders_food_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food',
        ),
        migrations.AddField(
            model_name='orders',
            name='food',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='main.foods'),
        ),
    ]
