# Generated by Django 4.0.4 on 2022-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Сумма'),
        ),
    ]
