# Generated by Django 4.0.4 on 2022-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='Адрес эл. почты')),
                ('stuff', models.CharField(max_length=100, verbose_name='Желаемая должность')),
                ('resume', models.FileField(upload_to='MEDIA_ROOT', verbose_name='Резюме')),
                ('message', models.TextField(verbose_name='Сопроводительное письмо')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
    ]
