# Generated by Django 4.0.4 on 2022-08-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
