# Generated by Django 4.0.4 on 2022-08-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('food_count', models.IntegerField(default=None, null=None, verbose_name='Кол-во')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, null=None, verbose_name='Время заказа')),
                ('food', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='main.foods')),
            ],
        ),
    ]
