# Generated by Django 4.0.4 on 2022-08-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
