# Generated by Django 4.0.4 on 2022-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_ratingstar_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(verbose_name='звезда'),
        ),
    ]
