# Generated by Django 4.0.4 on 2022-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_rating_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='resume',
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
